from . import account_move
from . import account_move_line
from . import base
from . import fleet_vehicle_model_brand
from . import fleet_vehicle_model
from . import fleet_vehicle_warranty_line
from . import fleet_vehicle
from . import product_template
from . import stock_move_line
from . import stock_picking
from . import project_project
from . import project_task
from . import sale_order
from . import sale_order_line
from . import service_template
from . import service_order_line_product
from . import service_order_line_service
from . import service_order_line
from . import service_order_worksheets
from . import service_order